/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestErrorRouteImport } from './routes/test-error'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBecomeRiderRouteImport } from './routes/_authenticated/become-rider'
import { Route as AuthenticatedAddressesRouteImport } from './routes/_authenticated/addresses'
import { Route as AuthenticatedRetailerOrdersRouteImport } from './routes/_authenticated/retailer.orders'
import { Route as AuthenticatedRetailerCustomersRouteImport } from './routes/_authenticated/retailer.customers'
import { Route as AuthenticatedOrdersIdRouteImport } from './routes/_authenticated/orders_.$id'
import { Route as AuthenticatedBookCylinderIdRouteImport } from './routes/_authenticated/book.$cylinderId'
import { Route as AuthenticatedAdminRidersRouteImport } from './routes/_authenticated/admin.riders'
import { Route as AuthenticatedAdminOrdersRouteImport } from './routes/_authenticated/admin.orders'
import { Route as AuthenticatedAdminCylindersRouteImport } from './routes/_authenticated/admin.cylinders'
import { Route as AuthenticatedAdminCommissionSettingsRouteImport } from './routes/_authenticated/admin.commission-settings'
import { Route as AuthenticatedAdminAdminsRouteImport } from './routes/_authenticated/admin.admins'

const TestErrorRoute = TestErrorRouteImport.update({
  id: '/test-error',
  path: '/test-error',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBecomeRiderRoute =
  AuthenticatedBecomeRiderRouteImport.update({
    id: '/become-rider',
    path: '/become-rider',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAddressesRoute = AuthenticatedAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRetailerOrdersRoute =
  AuthenticatedRetailerOrdersRouteImport.update({
    id: '/retailer/orders',
    path: '/retailer/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRetailerCustomersRoute =
  AuthenticatedRetailerCustomersRouteImport.update({
    id: '/retailer/customers',
    path: '/retailer/customers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdersIdRoute = AuthenticatedOrdersIdRouteImport.update({
  id: '/orders_/$id',
  path: '/orders/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookCylinderIdRoute =
  AuthenticatedBookCylinderIdRouteImport.update({
    id: '/book/$cylinderId',
    path: '/book/$cylinderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRidersRoute =
  AuthenticatedAdminRidersRouteImport.update({
    id: '/admin/riders',
    path: '/admin/riders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminOrdersRoute =
  AuthenticatedAdminOrdersRouteImport.update({
    id: '/admin/orders',
    path: '/admin/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCylindersRoute =
  AuthenticatedAdminCylindersRouteImport.update({
    id: '/admin/cylinders',
    path: '/admin/cylinders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminCommissionSettingsRoute =
  AuthenticatedAdminCommissionSettingsRouteImport.update({
    id: '/admin/commission-settings',
    path: '/admin/commission-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdminsRoute =
  AuthenticatedAdminAdminsRouteImport.update({
    id: '/admin/admins',
    path: '/admin/admins',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/test-error': typeof TestErrorRoute
  '/addresses': typeof AuthenticatedAddressesRoute
  '/become-rider': typeof AuthenticatedBecomeRiderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/commission-settings': typeof AuthenticatedAdminCommissionSettingsRoute
  '/admin/cylinders': typeof AuthenticatedAdminCylindersRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/riders': typeof AuthenticatedAdminRidersRoute
  '/book/$cylinderId': typeof AuthenticatedBookCylinderIdRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/retailer/customers': typeof AuthenticatedRetailerCustomersRoute
  '/retailer/orders': typeof AuthenticatedRetailerOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/test-error': typeof TestErrorRoute
  '/addresses': typeof AuthenticatedAddressesRoute
  '/become-rider': typeof AuthenticatedBecomeRiderRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/commission-settings': typeof AuthenticatedAdminCommissionSettingsRoute
  '/admin/cylinders': typeof AuthenticatedAdminCylindersRoute
  '/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/admin/riders': typeof AuthenticatedAdminRidersRoute
  '/book/$cylinderId': typeof AuthenticatedBookCylinderIdRoute
  '/orders/$id': typeof AuthenticatedOrdersIdRoute
  '/retailer/customers': typeof AuthenticatedRetailerCustomersRoute
  '/retailer/orders': typeof AuthenticatedRetailerOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/test-error': typeof TestErrorRoute
  '/_authenticated/addresses': typeof AuthenticatedAddressesRoute
  '/_authenticated/become-rider': typeof AuthenticatedBecomeRiderRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/_authenticated/admin/commission-settings': typeof AuthenticatedAdminCommissionSettingsRoute
  '/_authenticated/admin/cylinders': typeof AuthenticatedAdminCylindersRoute
  '/_authenticated/admin/orders': typeof AuthenticatedAdminOrdersRoute
  '/_authenticated/admin/riders': typeof AuthenticatedAdminRidersRoute
  '/_authenticated/book/$cylinderId': typeof AuthenticatedBookCylinderIdRoute
  '/_authenticated/orders_/$id': typeof AuthenticatedOrdersIdRoute
  '/_authenticated/retailer/customers': typeof AuthenticatedRetailerCustomersRoute
  '/_authenticated/retailer/orders': typeof AuthenticatedRetailerOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/test-error'
    | '/addresses'
    | '/become-rider'
    | '/dashboard'
    | '/orders'
    | '/admin/admins'
    | '/admin/commission-settings'
    | '/admin/cylinders'
    | '/admin/orders'
    | '/admin/riders'
    | '/book/$cylinderId'
    | '/orders/$id'
    | '/retailer/customers'
    | '/retailer/orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/test-error'
    | '/addresses'
    | '/become-rider'
    | '/dashboard'
    | '/orders'
    | '/admin/admins'
    | '/admin/commission-settings'
    | '/admin/cylinders'
    | '/admin/orders'
    | '/admin/riders'
    | '/book/$cylinderId'
    | '/orders/$id'
    | '/retailer/customers'
    | '/retailer/orders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/test-error'
    | '/_authenticated/addresses'
    | '/_authenticated/become-rider'
    | '/_authenticated/dashboard'
    | '/_authenticated/orders'
    | '/_authenticated/admin/admins'
    | '/_authenticated/admin/commission-settings'
    | '/_authenticated/admin/cylinders'
    | '/_authenticated/admin/orders'
    | '/_authenticated/admin/riders'
    | '/_authenticated/book/$cylinderId'
    | '/_authenticated/orders_/$id'
    | '/_authenticated/retailer/customers'
    | '/_authenticated/retailer/orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  TestErrorRoute: typeof TestErrorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-error': {
      id: '/test-error'
      path: '/test-error'
      fullPath: '/test-error'
      preLoaderRoute: typeof TestErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/become-rider': {
      id: '/_authenticated/become-rider'
      path: '/become-rider'
      fullPath: '/become-rider'
      preLoaderRoute: typeof AuthenticatedBecomeRiderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/addresses': {
      id: '/_authenticated/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AuthenticatedAddressesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retailer/orders': {
      id: '/_authenticated/retailer/orders'
      path: '/retailer/orders'
      fullPath: '/retailer/orders'
      preLoaderRoute: typeof AuthenticatedRetailerOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/retailer/customers': {
      id: '/_authenticated/retailer/customers'
      path: '/retailer/customers'
      fullPath: '/retailer/customers'
      preLoaderRoute: typeof AuthenticatedRetailerCustomersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders_/$id': {
      id: '/_authenticated/orders_/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AuthenticatedOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/book/$cylinderId': {
      id: '/_authenticated/book/$cylinderId'
      path: '/book/$cylinderId'
      fullPath: '/book/$cylinderId'
      preLoaderRoute: typeof AuthenticatedBookCylinderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/riders': {
      id: '/_authenticated/admin/riders'
      path: '/admin/riders'
      fullPath: '/admin/riders'
      preLoaderRoute: typeof AuthenticatedAdminRidersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/orders': {
      id: '/_authenticated/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/cylinders': {
      id: '/_authenticated/admin/cylinders'
      path: '/admin/cylinders'
      fullPath: '/admin/cylinders'
      preLoaderRoute: typeof AuthenticatedAdminCylindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/commission-settings': {
      id: '/_authenticated/admin/commission-settings'
      path: '/admin/commission-settings'
      fullPath: '/admin/commission-settings'
      preLoaderRoute: typeof AuthenticatedAdminCommissionSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/admins': {
      id: '/_authenticated/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AuthenticatedAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddressesRoute: typeof AuthenticatedAddressesRoute
  AuthenticatedBecomeRiderRoute: typeof AuthenticatedBecomeRiderRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedAdminAdminsRoute: typeof AuthenticatedAdminAdminsRoute
  AuthenticatedAdminCommissionSettingsRoute: typeof AuthenticatedAdminCommissionSettingsRoute
  AuthenticatedAdminCylindersRoute: typeof AuthenticatedAdminCylindersRoute
  AuthenticatedAdminOrdersRoute: typeof AuthenticatedAdminOrdersRoute
  AuthenticatedAdminRidersRoute: typeof AuthenticatedAdminRidersRoute
  AuthenticatedBookCylinderIdRoute: typeof AuthenticatedBookCylinderIdRoute
  AuthenticatedOrdersIdRoute: typeof AuthenticatedOrdersIdRoute
  AuthenticatedRetailerCustomersRoute: typeof AuthenticatedRetailerCustomersRoute
  AuthenticatedRetailerOrdersRoute: typeof AuthenticatedRetailerOrdersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddressesRoute: AuthenticatedAddressesRoute,
  AuthenticatedBecomeRiderRoute: AuthenticatedBecomeRiderRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedAdminAdminsRoute: AuthenticatedAdminAdminsRoute,
  AuthenticatedAdminCommissionSettingsRoute:
    AuthenticatedAdminCommissionSettingsRoute,
  AuthenticatedAdminCylindersRoute: AuthenticatedAdminCylindersRoute,
  AuthenticatedAdminOrdersRoute: AuthenticatedAdminOrdersRoute,
  AuthenticatedAdminRidersRoute: AuthenticatedAdminRidersRoute,
  AuthenticatedBookCylinderIdRoute: AuthenticatedBookCylinderIdRoute,
  AuthenticatedOrdersIdRoute: AuthenticatedOrdersIdRoute,
  AuthenticatedRetailerCustomersRoute: AuthenticatedRetailerCustomersRoute,
  AuthenticatedRetailerOrdersRoute: AuthenticatedRetailerOrdersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  TestErrorRoute: TestErrorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
